### ISSUE TITLE
Broken in Bolt 2.2.1

### ISSUE THREAD

**Issue by Largo** [bacbos/bolt-menu-editor#10]
Hi!

It seems like that this good extension won't work under Bolt 2.2.1.
After the update, adding new menuitems didn't work anymore.

I get this response when adding new items:
"{"status":0,"html":{"headers":{}}}"

I can't really pinpoint the issue. Just leaving this here.
Maybe it's my configuration?

**Comment by bacbos** [comment]
Hi @Largo 
You're right, something has changed since Bolt 2.2.x. I've published a fix for the menu editor just now (version 2.1.1), let me know if that works for you :+1:

**Comment by Largo** [comment]
Yes! It works. You are my hero :) :+1: :+1: :+1: 
However, searching through all contenttypes still doesn't work. 
 When the ct parameter is empty, the response is the html of the menueditor page instead of a json records array.

**Comment by bacbos** [comment]
Opps, you're right @Largo , didn't notice that one...
Found the bug and will push a fix soon, give me a day or two :)

**Comment by Largo** [comment]
No worries. You already helped me a ton with the first fix :)

2015-06-14 22:28 GMT+02:00 Steven Wüthrich <notifications@github.com>:
